routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\ActivosController;
use App\Http\Controllers\Admin\BajarsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [AuthController::class,'loginform']);
Route::get('login', [AuthController::class,'loginform']);
Route::get('admin', [AuthController::class,'loginform']);
Route::post('login', [ 'as' => 'login', 'uses' => 'App\Http\Controllers\AuthController@login']);
Route::get('logout', [AuthController::class,'logout']);
Route::get('register', [AuthController::class,'registrationForm']);

Route::group(['middleware'=>['auth'], 'prefix' => 'admin'], function(){
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::resource('users', UsersController::class);
    Route::resource('activos', ActivosController::class);
    Route::resource('bajas', BajasController::class);
    Route::post('activos/{id}/dar_baja', [ActivosController::class,'dar_baja']);
    
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'last_name',
        'email',
        'mobile',
        'dob',        
        'password',
        'role',
        'image'
    ];
    protected $dates = ['deleted_at'];
    protected $images_attr = ['image'];
    protected $folder_images = 'users_images';

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function scopeUsers($query)
    {
        return $query->where('role','<>','admin');
    }

    public function getFullNameAttribute()
    {
        return "{$this->name} {$this->last_name}";
    }
    //MUTATOR
    public function getImagePathAttribute()
    {
        if ($this->image)
            return asset('img') .'/'.$this->folder_images.'/'.$this->image;
        else
            return asset('img/no-image.png');
    }
}

resources/views/admin/partials/_upload.blade.php
    
    <!--  <i class="fa fa-plus imgAdd"></i>-->

  

    <script type="text/javascript" charset="utf-8">
        
    </script>




  <div id="cropperModal" class="modal fade" role="dialog" style="display: none;">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content" style="width: 642px;">
        <div class="modal-header head-login">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="modal-cropper-body" style="text-align: center">
  
            <div>
              <img id="img-holder" class="img-holder"/>
            </div>
  
            <button id="crop-select" class="btn btn-primary" type="submit">Crop</button>
            <button class="btn btn-warning" data-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  

resources/views/admin/partials/breadcrumb.blade.php
<h2 class="pageheader-title">{{$title}}</h2>
<div class="page-breadcrumb">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ url('/admin/dashboard') }}" class="breadcrumb-link">
                    {{ ucfirst(trans('common.home')) }}
                </a>
            </li>
            @foreach ($breadcrumbs['text'] as $key=>$item)
                
                <li class="breadcrumb-item">
                    <a href="{{ $breadcrumbs['url'][$key]}}" class="breadcrumb-link">
                        {{ $item }}
                    </a>
                </li>    
            @endforeach
            <li class="breadcrumb-item active" aria-current="page">
                {{ $final }}
            </li>
        </ol>
    </nav>
</div>    

resources/views/admin/partials/buttons.blade.php
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-4 col-md-10 text-center">
            @if (!isset($label))
                <button type="submit" class="btn btn-primary" >{{ ucfirst(trans('common.create')) }}</button>    
            @else
                <button type="submit" class="btn btn-primary" >{{ ucfirst(trans('common.update')) }}</button>
            @endif            
            <a href="{{ URL::previous() }}" class="btn btn-inverse">{{ ucfirst(trans('common.cancel')) }}</a>
        </div>
    </div>
</div>

resources/views/admin/partials/buttons_users.blade.php
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-4 col-md-8">
            @if(isset($user) )
                <button type="submit" class="btn btn-warning blank_password">{{$label_blank_password}}</button>
            @endif
            @if(!isset($user))
            <button type="submit" class="btn btn-primary">{{$label}}</button>
            @endif
            <a href="{{ URL::previous() }}" class="btn btn-default">Cancelar</a>
        </div>
    </div>
</div>

resources/views/admin/partials/buttonsfront.blade.php
<div class="form-actions">
    <div class="row">
        <div class="col-md-offset-4 col-md-8">
            <button type="submit" class="btn btn-primary">{{$label}}</button>
        </div>
    </div>
</div>

resources/views/admin/partials/errors.blade.php
@if ($errors->any())
    <ul class="alert alert-danger">
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif

resources/views/admin/partials/map.blade.php
<div class="form-group row">
    <div class="col-md-4"></div>
    <div class="col-md-8">
        <h6 class="help-block">Su ubicación en el mapa es importante, mueva el marker a su dirección</h6>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-8">
        <div id="mapa" style="height: 400px;width:600px"></div>
    </div>    
</div>

<div class="form-group row">
    <div class="col-lg-12 text-right">
        {!! Form::hidden('lat', null, ['class' => 'form-control', 'id' => 'lat1', 'required']) !!}
        {!! Form::hidden('lng', null, ['class' => 'form-control', 'id' => 'lng1', 'required']) !!}
        {!! $errors->first('lng', '<h4 class="help-block">Su ubicacion en el mapa es importante, mueva el marker a su dirección</h4>') !!}
    </div>                            
</div>

resources/views/admin/partials/messages.blade.php
@if (Session::has('flash_message') and Session::get('flash_message')!= 'You must be logged in')
    <div class="alert alert-{{ Session::get('flash_message_type') }}">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        {{ Session::get('flash_message') }}
    </div>
    @section('scripts')
        <script>
            $(document).ready(function() {
                setTimeout(function () {
                    toastr.options = {
                        closeButton: true,
                        progressBar: true,
                        showMethod: 'slideDown',
                        timeOut: 4000
                    };
                    toastr['{{ Session::get('flash_message_type') }}']('{{ Session::get('flash_message') }}', 'GROUP GIFT: ');
                }, 1300);
            })
        </script>
    @endsection
@endif

resources/views/admin/partials/searcher.blade.php
{!! Form::open([
    'id'=>'paginate',
    'url' => $url, 
    'method' => 'GET', 
    'enctype' => 'multipart/form-data', 
    'class' => 'form-horizontal pt-3',
    'autocomplete'=>'off'
]) !!}  
    <div class="card d-flex flex-row justify-content-around p-5">
        <div class="flex-grow-1">
            <span id="date-label-to" class="date-label col-md-4 form-control-label">{{ ucfirst(trans('common.display')) }}</span>
            {!! Form::select('pagination',['10'=>'10','20'=>'20','50'=>'50','100'=>'100','500'=>'500'],$paginate,['class'=>'display custom-select custom-select-sm col-md-4 form-control-sm']) !!}
            <span id="date-label-to" class="date-label col-md-4 form-control-label"> {{ ucfirst(trans('common.records')) }}</span>
        </div>
        <div class="flex-grow-1">
            <div class="d-flex flex-row">
                @if ($section == 'lunches')
                    <div class="input-group date col-md-4 p-0" id="lunch_search" data-target-input="nearest">
                        {!! Form::text('lunch_search', null, ['class' => 'form-control datetimepicker-input', 'name'=>'keyword', 'data-target' => '#lunch_search']) !!}
                        {!! $errors->first('date', '<p class="help-block">:message</p>') !!}
                        <div class="input-group-append" data-target="#lunch_search" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-sm">
                        <i class="fas fa-search"></i>
                    </button>
                @else
                    <div class="flex-grow-1"> 
                        {!! Form::text('keyword', null, ['class' => 'form-control form-control-sm', 'placeholder' => isset($example)?$example:ucfirst(trans('common.search')).'...']) !!}
                    </div>
                    <div class="flex-grow-1"> 
                        <button type="submit" class="btn btn-primary btn-sm">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>   
                @endif
            </div>
            @if ($section == 'drinks')
                <div class="d-flex flex-row">
                    <div class="form-check form-check-inline">
                        @foreach ($types_list as $key=>$type)
                        <div class="icheck-primary d-inline ml-2">
                            <input type="radio" id="{{$type}}" name="key_type" value="{{$key}}">
                            <label for="{{$type}}">
                                {{ucfirst($type)}}
                            </label>
                        </div>
                        @endforeach
                    </div>
                </div>    
            @endif
        </div>
    </div> 
{!! Form::close() !!}

resources/views/admin/partials/upload_image.blade.php
{{---------- Imagen --}}
<div class="form-group row">
    {!! Form::label('label_act', ucfirst(trans('common.previewact')), ['class' => 'col-md-4
    form-control-label text-md-right']) !!}
    <div class="col-md-8">
        <img src="{{ $collection?$collection->image_path:asset('img/no-image.png') }}" class="img-fluid w-20" />
    </div>
</div>
<div class="form-group row {{ $errors->has('image') ? 'has-error' : ''}}">
    {!! Form::label('label_insert', ucfirst(trans('common.image')), ['class' => 'col-md-4 form-control-label text-md-right']) !!}
    <div class="col-md-4 fileContainer">
        {!! Form::file('image', ['class' => 'col-md-6', 'id' =>
        'image','accept'=>"image/x-png,image/gif,image/jpeg"]) !!}
        {!! $errors->first('image_error', '<p class="help-block">:message</p>') !!}
        <span class="btn btn-success width">
            <i class="fas fa-images"></i>
            {{ucfirst(trans('common.select_image'))}}
        </span>
    </div>
</div>
<div class="form-group row">
    {!! Form::label('result_preview', ucfirst(trans('common.preview')), ['class' => 'col-md-4 form-control-label text-md-right']) !!}
    <img src="" alt="" id="preview" class="img-fluid d-none prev-img">
</div>
{{------ end imagen ---------}}